version: '3'

services:
  api:
    image: node:fermium-alpine
    command: npm run start
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app

  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017
  
 
